### ISSUE TITLE
Hi this is MJC I just wanted to know if the game isn't finished yet or if there is just a bug with logging in.

### ISSUE THREAD

**Issue by ILoveMinescraft2** [notalicialol/Chocolet#1]

**Comment by notalicialol** [comment]
Chocolet is currently under heavy development, and will not be open to the public until late May to early July.

There is no bug with logging in because I didn't make the login page yet, and you'd need to set up a MongoDB server in order to host your own instance of Chocolet.

The official version of Chocolet is just playable at https://chocolet.xyz when it releases.

**Comment by zastlx** [comment]
skibidi ohio rizzler
